### ISSUE TITLE
Naver Papago is not working

### ISSUE THREAD

**Issue by thamfpt** [scottgigante/korean-support#19]
Hello. Thank you for creating this addon. But I encountered a problem. My Naver Papago audio does not work. Although I chose Naver Papago. Audio files only work with Google TTS, but I don't like this voice very much. Hope you read this comment and help me solve it. Thanks
![1](https://user-images.githubusercontent.com/67628330/89425896-b795bf80-d763-11ea-9ef8-40ec36ba3908.jpg)
![2](https://user-images.githubusercontent.com/67628330/89425898-b8c6ec80-d763-11ea-930d-460d7f20e460.jpg)

**Comment by cereska** [comment]
I have been also experiencing the same. Naver Papago has stopped working entirely, it can no longer download sounds. Only Google TTS works, but I don't like it and it would love to have this issue fixed. Below is the error message while in Debug mode, hope this helps:
![image](https://user-images.githubusercontent.com/51246982/89707185-2e9da480-d96c-11ea-89b7-6cb3eed0de0f.png)

Propably Naver has updated their API...

**Comment by totalfish1** [comment]
I think the API url has changed https://apidocs.ncloud.com/en/ai-naver/clova_speech_synthesis/

**Comment by scottgigante** [comment]
The API has indeed changed. The new API requires an API key, which appears
to be free but somewhat involved. This is something I plan to get to
eventually, but frankly is pretty low on my priority list. If somebody
wants to contribute a PR to https://github.com/scottgigante/NaverTTS to
adopt the new API, I would gladly review and merge it.

**Comment by totalfish1** [comment]
@scottgigante Cool ill see what i can do. I'm not too familiar with python but I can give it a go.

**Comment by scottgigante** [comment]
Hardest thing will be getting access to the API. If you can find me the
format for the POST request and an API key, I am happy to do the rest.

**Comment by Sleeping-Donut** [comment]
I think you can just use this from naver dictionary right?

`https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&text=`TEXT`&speaker=`SPEAKER

with the speakers being listed here: https://apidocs.ncloud.com/en/ai-naver/clova_voice/tts-basic/

**Comment by scottgigante** [comment]
Brilliant! I'll give this a go.

**Comment by scottgigante** [comment]
This should be fixed and the change uploaded to ankiweb. Please let me know if it works for you!
