### ISSUE TITLE
Naver and Papago and google audio doesn't work

### ISSUE THREAD

**Issue by EvaChibiz** [scottgigante/korean-support#20]
A week ago those sites seem to have changed their IPA, so right now add-on reports an error if one tries to run "fill missing sounds"
=(
Thank you for the great app

**Comment by scottgigante** [comment]
Duplicate of #19.

The API has indeed changed. The new API requires an API key, which appears
to be free but somewhat involved. This is something I plan to get to
eventually, but frankly is pretty low on my priority list. If somebody
wants to contribute a PR to https://github.com/scottgigante/NaverTTS to
adopt the new API, I would gladly review and merge it.

**Comment by scottgigante** [comment]
This should be fixed and the change uploaded to ankiweb. Please let me know if it works for you!

**Comment by EvaChibiz** [comment]
Yes, everything works perfectly!
Thank you very much for your hard work😍

Отправлено с iPhone

**Comment by scottgigante** [comment]
Great! I'm glad to hear it.
