### ISSUE TITLE
Papago Still Doesn't Work for Me.

### ISSUE THREAD

**Issue by Frannilea** [scottgigante/korean-support#22]
Sorry it took so long to test it.  But neither Papago or Google works for me.  When I put the Korean word into the top field, and click on the next field to type English, the cursor just moves there. Nothing else happens.  I still have to go and retrieve the file manually from Papago or Google through Firefox.

Have you heard from anyone else?  Are theirs working?

Thanks in advance. :-)

**Comment by scottgigante** [comment]
Yes, this is working for others. Can you turn on debug mode in settings? Also, have you made sure that the 한글 button in the top right is pressed?

**Comment by Frannilea** [comment]
Ah!  I didn't have the 한글 button pressed!!  Thank you!!  And thank you
SOOOO MUCH for fixing this add-on!!  I love it!!! :-)))

**Comment by scottgigante** [comment]
So glad it's working! I'm glad you're enjoying the add-on :)
