### ISSUE TITLE
No module called 'gtts' error upon loading up Anki 

### ISSUE THREAD

**Issue by Jimmycheong** [scottgigante/korean-support#24]
It appears the latest release is throwing this error when loading up Anki. 

Could it be possible that module **gtts** is missing from the requirements.txt file? It also doesn't show the 한글 button when adding new cards anymore

![image](https://user-images.githubusercontent.com/22529514/107161506-029fc200-6995-11eb-844e-a6fdc5d195f4.png)

**Comment by cereska** [comment]
I just logged in to report the same issue, so I'm just gonna chime in with more debug info:
    
    Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2021-02-07 14:53:59
    
    Korean Support ['1336389630', 2021-02-04T15:33, 'None', mod]
       


![image](https://user-images.githubusercontent.com/51246982/107204778-5fcf5e00-69fd-11eb-9785-45fa44d6f917.png)

Fingers crossed it can be fixed soon 🤞

**Comment by scottgigante** [comment]
Thanks both for the details. This should be resolved now. Please confirm (and if you left a note on the ankiweb page, please update your review if it's working :) )

**Comment by Jimmycheong** [comment]
Awesome Scott! Thanks for the rapid response.
