### ISSUE TITLE
Feature Request "fill incomplete notes" is missing a hanja fill option

### ISSUE THREAD

**Issue by michaelcward1996** [scottgigante/korean-support#26]
It would be so awesome if that was a thing. For my use case, I already have a large nicely sorted deck of about 7 thousand words. I've been able to fill the hanja on a couple of hundred cards. With these, I've been able to combine the various anki hanja decks so that now those words have the English meaning of the hanja, a break down of the radicals, and a couple examples of them in other vocabulary. I would absolutely love the chance to make my entire collection that way. Thanks for the work, this addon is a huge timesaver. :)

**Comment by scottgigante** [comment]
Didn't realise this wasn't available! I've just added it. Let me know if you have any issues.

**Comment by michaelcward1996** [comment]
Thanks so much! It works great :)
