### ISSUE TITLE
is it possible to import from a csv and still get the sounds?

### ISSUE THREAD

**Issue by TheRealDani** [scottgigante/korean-support#37]
Just discovered your add-on. really nice. If I add a card and enter the Korean, it automatically
adds a sound.
If I import a list from a csv, fields match up,etc - it doesn't create sounds for any of them.
Is there a way to do this or only works if I add one card at a time?

Thanks!
dan

**Comment by TheRealDani** [comment]
Hi.
That worked!
amazing.
I had not discovered the plug-in menu!

Thanks so much for your help!

dan

**Comment by scottgigante** [comment]
You're welcome! Glad I could help.
