### ISSUE TITLE
add on didn't fill the translate, Silhouette

### ISSUE THREAD

**Issue by tuhuynhh** [scottgigante/korean-support#4]
<img width="494" alt="erro" src="https://user-images.githubusercontent.com/62436867/77994459-46c53d80-7354-11ea-93f7-ea7325be85a7.PNG">
Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "C:\Users\ADMIN\AppData\Roaming\Anki2\addons21\1336389630\fill_missing.py", line 152, in fill_translation
    ['english'], note_dict))
<class 'KeyError'>: 'english'

**Comment by scottgigante** [comment]
Thanks for the report -- this should be fixed in `0.7-beta`. I'll release this on Anki Shared today.
