### ISSUE TITLE
Latest update causes crash of this addon when Anki 2.1.35 loads 

### ISSUE THREAD

**Issue by cereska** [scottgigante/korean-support#42]
Hi,

I have to stay on Anki 2.1.35 due to another addon not updating.
When I updated Korean Support today, I got following error when the application loaded:
![obraz](https://github.com/scottgigante/korean-support/assets/51246982/e2bbbf6e-bdb3-4dde-bc40-d71ffa4f9d9b)
Can you please take a look what might be causing this?
Many thanks in advance!

**Comment by scottgigante** [comment]
Thanks for letting me know -- I released a new version yesterday for compatibility with Anki 2.10 and this appears to have broken the older version.

I released a new version just now that should hopefully work on both branches. Can you please update it and let me know how it goes?

**Comment by cereska** [comment]
I updated the add-on and now another error shows up:

![obraz](https://github.com/scottgigante/korean-support/assets/51246982/b1f18f85-d179-4764-83fb-7d333c9623fb)

**Comment by Kiina** [comment]
> I released a new version just now that should hopefully work on both branches. Can you please update it and let me know how it goes?

The bugfix broke all versions. Seems like anki wants `from aqt.qt` instead of `from aqt.qt.QtWidgets`. Downloaded an old qt5 anki version and it seems to work.

**Comment by scottgigante** [comment]
Updated, please check again. Thanks

**Comment by Kiina** [comment]
Startup doesnt crash but about box is broken. I'm looking into it

**Comment by cereska** [comment]
It doesn't crash on load anymore for me :)

**Comment by scottgigante** [comment]
Thanks for letting me know and thanks @Kiina for the quick PR!
