### ISSUE TITLE
Doesn't download voice when Google TTS engine is selected

### ISSUE THREAD

**Issue by Emariel** [scottgigante/korean-support#6]
It fills the "Sound" fields nice when Naver Papago voice is selected. But when I choose Google TTS in settings and click "Fill missing sounds", it shows the error that download is failed every time.

![20200413-02](https://user-images.githubusercontent.com/52016621/79082770-67fd3500-7d29-11ea-9150-51aad24de231.png)

Windows 10 1903 (x64), Anki Version 2.1.22 (0ecc189a)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1

**Comment by scottgigante** [comment]
Hi @Emariel , I'm having trouble tracing the source of this error. I've modified the package to improve error tracing within TTS -- any chance you can extract the contents of this new package to `C:\Users\Emma\AppData\Roaming\Anki2\addons21\1336389630\`, try again, and show me the new error?

[korean.zip](https://github.com/scottgigante/korean-support/files/4469811/korean.zip)

**Comment by Emariel** [comment]
> 
![20200414-04](https://user-images.githubusercontent.com/52016621/79210687-7fc9db80-7e45-11ea-861b-8029fc61c3e2.png)

By the way, I've found another solution. As I wanted male voice for my cards, I found out how to make it download male voice from NAVER Papago (by default it takes female voice).
I located 2 files in the folder ...Anki2\addons21\1336389630\lib\navertts - constants.py and tts.py. In both files in the line "gender" I just changed the letter "f" to "m". Now it works as I wanted.
So, I have a suggestion for the future updates: to add an ability to switch Naver voice gender in the Preferences menu. Thank you for help anyway.

**Comment by scottgigante** [comment]
Thanks for the updated error message and the suggestion! I'll add that ability in the next update.

**Comment by scottgigante** [comment]
@Emariel you can now select gender and speed within the TTS menu. Enjoy!

**Comment by Emariel** [comment]
Thank you very much!
