### ISSUE TITLE
Request for contribution guide

### ISSUE THREAD

**Issue by leeyspaul** [scottgigante/korean-support#7]
It would be nice to have a CONTRIBUTION.md to detail how people can contribute if they'd like to.

Would it be a possibility? Also happy to write one as I'm looking into contributing!

**Comment by scottgigante** [comment]
Hi @leeyspaul , I'd love to have your help! We currently have three open issues marked as `help wanted` which I don't have bandwidth to resolve right now. I'll also add a CONTRIBUTING.md to encourage others to join us! Thanks for the suggestion.
